# Generated by Django 3.2.4 on 2021-08-17 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teatime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('tea', models.CharField(choices=[('B', 'Breakfast Blend'), ('G', 'Green Tea'), ('C', 'Chamomile'), ('P', 'Peppermint')], default='B', max_length=1)),
                ('mug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.mug')),
            ],
        ),
    ]
