# Generated by Django 3.2.4 on 2021-08-18 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_teatime'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterModelOptions(
            name='teatime',
            options={'ordering': ['-date']},
        ),
        migrations.AlterField(
            model_name='teatime',
            name='date',
            field=models.DateField(verbose_name='Choose a Time For Tea'),
        ),
        migrations.AddField(
            model_name='mug',
            name='coasters',
            field=models.ManyToManyField(to='main_app.Coaster'),
        ),
    ]
